'/etc/cron.allow':
  'neq': 
    'values': 
      'No such file or directory':
        'severity': YELLOW
        'msg': No /etc/cron.allow has been set up.

  'permissions':
    'other':
      'w': 
        'severity': RED
        'msg': Any user can edit /etc/cron.allow.
        

'/etc/at.allow':
  'neq': 
    'values': 
      'No such file or directory':
        'severity': YELLOW
        'msg': No /etc/at.allow has been set up.
      
  'permissions':
    'other':
      'w': #in code: checks if w is in the last three permissions [rwx]
        'severity': RED
        'msg': Any user can edit /etc/at.allow.