'/dev': 
  'use%': 
    ngt: 
      value: 75
      severity: BLUE
      msg: The /dev file system is over 75% capacity.
         
'/':
  'use%':
    ngr:
      value: 65
      severity: BLUE
      msg: The / filesystem is over 65% capactiy.
      
'default':
  'use%': 
    ngr: 
      value: 90
      severity: YELLOW
      msg: The filesystem /fs/ is over 90% capacity
  'filesystem':
    neq:
      values:
        'nfs':
          severity: YELLOW
          msg: The filesystem /fs/ is a NFS system.